#!/bin/bash
i3_folder="$HOME/.config/i3"
i3_config_file="$i3_folder/config"
i3_config_dir="$i3_folder/config.d"
i3_includes_file="$i3_config_dir/i3_configs.conf"

if [[ -f "$i3_includes_file" ]]; then
  [[ -f "$i3_config_file" ]] && rm "$i3_config_file"

  touch "$i3_config_file"

  echo "#### DO NOT EDIT THIS FILE, IT IS GENERATED." >> "$i3_config_file"
  echo "#### EDIT THE FILES HERE: $i3_folder/config.d/**/*" >> "$i3_config_file"

  include_file() {
    cat "$i3_config_dir/$1" >> "$i3_config_file"
  }

  get_file_name_from_line () {
    stripped_file_name=$(echo $* | sed 's/\(import \)\(.*.conf\)\(;\)/\2/')
    echo "$stripped_file_name"
  }

  exec 3< "$i3_includes_file"

  until [ "$done" ]
  do
    read <&3 config_line

    if [ $? != 0 ]; then
      done=1
      continue
    else
      if [[ "$config_line" == "import "* ]]; then
        file_name="$(get_file_name_from_line $config_line)"
        include_file "$file_name"
      fi
    fi
  done

  if [[ "$1" == "restart" || "$1" == "reload" ]]; then
    i3-msg "$1"
  fi
else
  echo "ERROR:"
  echo "Please create the configs import file:"
  echo " $i3_config_dir/i3_configs.conf"
fi
